apiVersion: apps/v1
kind: Deployment
metadata:
  name: queue-1

spec:
  selector:
    matchLabels:
      app: queue
  replicas: 1
  template:
    metadata:
      labels:
        app: queue
    spec:
      containers:
        - name: queue
          image: richardchesterwood/k8s-fleetman-queue:release2
          resources:
            requests:
              memory: 500Mi
              cpu: 1
            limits:
              memory: 1000Mi
              cpu: 1
      

