apiVersion: v1  ## version kubernetes API
kind: Pod  ## you are describing a pod
metadata:
  name: web-app  ## name of pod
spec:
  containers:
  - image: nginx  ## container image to create the container from
    name: web  ## name of the container
    ports:
    - containerPort: 80  ## the port the app is listening on
      protocol: TCP
