apiVersion: v1  ## version kubernetes API
kind: Service  ## ReplicationControl manifest type
metadata:
  name: web-app  ## name of ReplicationController
spec:
  ports:
  - name: http
    port: 8080
    targetPort: 80
  - name: https
    port: 443
    targetPort: 443
  selector:
    app: web-app-app
