apiVersion: apps/v1  ## version kubernetes API
kind: ReplicaSet  ## ReplicaSet manifest type
metadata:
  name: web-app  ## name of ReplicaSet
spec:
  replicas: 3  ## the desired number of pod instances
  selector:
    matchLabels:  ## You’re using the simpler matchLabels selector here, which is much like a ReplicationController’s selector.
      app: web-app-app  
  template:
    metadata:
      labels:
        app: web-app-app
    spec:
      containers:
      - name: web-container
        image: nginx
