apiVersion: v1
kind: Pod
metadata:
  name: pod-anywhere
  labels:
    region: us-west-1a
spec:
  containers:
  - name: nginx
    image: nginx
  affinity:
   nodeAffinity:
    requiredDuringSchedulingIgnoredDuringExecution:
     nodeSelectorTerms:
     - matchExpressions:
       - key: region
         operator: Exists  ## Exists komandasi ile mueyyen edirikki hansi nodun keyi key=region dursa demekki oradada yaransi. Artiq ona maraqli deyil values olaraq ne secilir