apiVersion: v1
kind: Pod
metadata:
  name: my-nginx-pod-2
  labels:
    region: us-west-1a
spec:
  containers:
  - name: nginx
    image: nginx
  affinity:
   nodeAffinity:
    requiredDuringSchedulingIgnoredDuringExecution:
     nodeSelectorTerms:
     - matchExpressions:
       - key: region
         operator: NotIn  ## o demekdirki asagida qeyd olunan values yeniki "us-west-1b" ile label olunmus node larda yaranmasin bu pod
         values:
         - us-west-1b
