apiVersion: v1
kind: Pod
metadata:
  name: my-nginx-pod
  labels:
    region: us-west-1a
spec:
  containers:
  - name: nginx
    image: nginx
  affinity:
   nodeAffinity:
    requiredDuringSchedulingIgnoredDuringExecution:
     nodeSelectorTerms:
     - matchExpressions:
       - key: region
         operator: In  ## o demekdirki yalniz asagida qeyd olunan values yeniki "us-west-1a,us-west-1b" ile label olunmus node larda yaransin bu pod
         values:
         - us-west-1a
         - us-west-1b