apiVersion: v1  ## version kubernetes API
kind: Pod  ## you are describing a pod
metadata:
  name: fortune  ## name of pod
spec:
  containers:
  - image: luksa/fortune  ## container image to create the container from
    name: html-generator  ## name of the container
    volumeMounts:    
    - name: html
      mountPath: /var/htdocs
  - image: nginx:alpine
    name: web-server
    volumeMounts:
    - name: html
      mountPath: /usr/share/nginx/html
      readOnly: true
    ports:
    - containerPort: 80  ## the port the app is listening on
      protocol: TCP
  volumes:
  - name: html
    emptyDir: {}
