apiVersion: v1  ## version kubernetes API
kind: Pod  ## you are describing a pod
metadata:
  name: gitrepo-volume-pod  ## name of pod
spec:
  containers:
  - image: nginx:alpine
    name: web-server
    volumeMounts:
    - name: html
      mountPath: /usr/share/nginx/html
      readOnly: true
    ports:
    - containerPort: 80  ## the port the app is listening on
      protocol: TCP
  volumes:
  - name: html
    gitRepo:
      repository: https://github.com/muradsamadov/kubia-website-example.git
      revision: master
      directory: .
