apiVersion: v1
kind: Pod
metadata:  
  name: web-app-1 
spec:  
  containers:  
  - image: nginx
    name: web-app-1    
    volumeMounts:    
    - name: my-pvc      
      mountPath: /var/www/html   
    ports:    
    - containerPort: 80   
      protocol: TCP  
  volumes:  
  - name: my-pvc    
    persistentVolumeClaim:             
      claimName: pvc-1
