apiVersion: v1  ## version kubernetes API
kind: PersistentVolumeClaim  ## you are describing a pod
metadata:
  name: pvc-1  ## name of pod
spec:
  resources:
    requests:
      storage: 1Gi
  accessModes:
  - ReadOnlyMany
  storageClassName: slow
