apiVersion: v1
kind: Pod
metadata:  
  name: mongodb 
spec:  
  containers:  
  - image: mongo    
    name: mongodb    
    volumeMounts:    
    - name: my-pvc      
      mountPath: /data/db    
    ports:    
    - containerPort: 27017      
      protocol: TCP  
  volumes:  
  - name: my-pvc    
    persistentVolumeClaim:             
      claimName: pvc-1
