apiVersion: v1
kind: Pod
metadata:  
  name: web-app 
spec:  
  containers:  
  - image: httpd
    name: web-app    
    volumeMounts:    
    - name: my-pvc      
      mountPath: /var/www/html   
    ports:    
    - containerPort: 80   
      protocol: TCP  
  volumes:  
  - name: my-pvc    
    persistentVolumeClaim:             
      claimName: pvc-1
