
apiVersion: v1
kind: ResourceQuota
metadata:
  name: quota-demo1
  namespace: quota-demo-ns
spec:
  hard:
    pods: "2"  ## max 2 pod yaratmaq olar
    configmaps: "1"  ## max 1 eded cm yaratmaq olar