apiVersion: v1
kind: Secret
metadata:
  name: mosquitto-secret-file
type: Opaque
data:
  secret.file: |  ##name of the config file. Bu bizim isleyen kontainerin config fayli ile eyni olmalidir. sohbet konfig faylin adindan gedir
    c29tZXN1cGVyc2VjcmV0IGZpbGUgY29udGVudHMgbm9ib2R5IHNob3VsZCBzZWU=
## yuxarida qeyd olunan base64 ile sifrelenmis sifredir