apiVersion: v1  ## version kubernetes API
kind: Service  ## ReplicationControl manifest type
metadata:
  name: back-end  ## name of ReplicationController
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 80
  selector:
    app: myapp
    type: back-end
