apiVersion: v1  
kind: PersistentVolumeClaim
metadata:
  name: mongo-pvc
spec:
  resources:
    requests:
      storage: 1Gi
  accessModes:
    - ReadWriteMany
  storageClassName: mylocalstorage

---
apiVersion: v1  
kind: PersistentVolume  
metadata:
  name: local-storage
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  storageClassName: mylocalstorage
  hostPath:
    path: "/mnt/some-new/directory/structure"
    type: DirectoryOrCreate
