apiVersion: v1
kind: Pod
metadata:
  name: nginx
  namespace: quota-demo-ns
spec:
  containers:
  - image: nginx
    name: nginx
    resources:
      limits:
        memory: "100Mi"  ## pod maksimum olaraq yeni limit olaraq 100Mi rami kecmeyecek