apiVersion: v1
kind: ResourceQuota
metadata:
  name: quota-demo-mem
  namespace: quota-demo-ns
spec:
  hard:
    limits.memory: "500Mi"  ## resurs limit olaraq bu ns de max 512 Mi ram olan pod islemelidir