apiVersion: v1  ## version kubernetes API
kind: Service  ## ReplicationControl manifest type
metadata:
  name: default-http-backend  ## name of ReplicationController
spec:
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  selector:
    run: default-reponse-app
