apiVersion: v1  ## version kubernetes API
kind: Service  ## ReplicationControl manifest type
metadata:
  name: nginx-deploy-blue  ## name of ReplicationController
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 80
    nodePort: 30008
  selector:
    run: nginx-main
