apiVersion: v1
kind: Pod
metadata:
  name: web
spec:
  containers:
    - name: web
      image: nginx
      volumeMounts: 
        - mountPath: /usr/share/nginx/html
          name: vol-web
      
  volumes:
    - name: vol-web
      hostPath: 
        path: /data
        type: DirectoryOrCreate