apiVersion: v1
kind: Pod
metadata:
  name: mysql-pod
  labels:
    app: myapp
    type: front-end

spec:
  containers:
    - name: mysql
      image: mysql:5.7
      ports:
        - containerPort: 3306
      envFrom:
        - secretRef:
            name: app-secret
        - configMapRef:
            name: app-config