apiVersion: v1  ## version kubernetes API
kind: Service  ## ReplicationControl manifest type
metadata:
  name: mysql-service  ## name of ReplicationController
spec:
  type: NodePort
  ports:
  - port: 3306
    targetPort: 3306
    nodePort: 30008
  selector:
    app: myapp
    type: front-end
