apiVersion: v1  
kind: Pod
metadata:
  name: web
  labels:
    app: myapp
    type: front-end
    
spec:
  containers:
    - name: my-web
      image: nginx
      volumeMounts:
        - mountPath: /usr/share/nginx/html
          name: my-pvc
  
  volumes:
    - name: my-pvc
      persistentVolumeClaim:
        claimName: pvc-1

